### ISSUE TITLE
Endless epoll_wait after losing connection

### ISSUE THREAD

**Issue by fsitedev** [tarantool/tarantool-perl#12]
Playback steps:
- Connect with DR::Tarantool::MsgPack::AsyncClient->connect
- Make a few requests to tnt
- Shutdown tnt
- Got errors:
```
Socket error: Server closed connection at
/usr/lib64/perl5/vendor_perl/DR/Tarantool/MsgPack/LLClient.pm line 196

Use of uninitialized value in ref-to-glob cast at
/usr/lib64/perl5/vendor_perl/DR/Tarantool/AEConnection.pm line 162.
```
-  Perl process has 100% cpu utilisation and repeats same calls in endless loop: 
```
clock_gettime(CLOCK_MONOTONIC, {3823045, 735767739}) = 0
clock_gettime(CLOCK_MONOTONIC, {3823045, 735808117}) = 0
epoll_wait(4, {}, 64, 0)                = 0
clock_gettime(CLOCK_MONOTONIC, {3823045, 735875377}) = 0
clock_gettime(CLOCK_MONOTONIC, {3823045, 735913431}) = 0
epoll_wait(4, {}, 64, 0)                = 0
clock_gettime(CLOCK_MONOTONIC, {3823045, 735982733}) = 0
clock_gettime(CLOCK_MONOTONIC, {3823045, 736029417}) = 0
epoll_wait(4, {}, 64, 0)                = 0
clock_gettime(CLOCK_MONOTONIC, {3823045, 736100634}) = 0
clock_gettime(CLOCK_MONOTONIC, {3823045, 736141469}) = 0
epoll_wait(4, {}, 64, 0)                = 0
```

**Comment by Awety** [comment]
Perl 5.14, works fine. In case there is no connection to tarantool we get 'Connection refused' error.
Perl 5.10  -- yes, the problem appears. I'll try to handle it somehow if it's possible.

**Comment by Awety** [comment]
## Code: branch `origin/loosing-connection-epoll_wait`


## I found the way to avoid the error.

It occured because all AnyEvent watchers has been deleted in case of connection error (AE::io was watching for read events and detected the error) and event loop has become empty, so it took 100% CPU.

So, the ways to aviod such a situation are the following:

1) You can 
```perl
use EV;
use AnyEvent;

use DR::Tarantool::MsgPack::AsyncClient;

my $cv = AnyEvent->condvar;
....your code here...
EV::run;
```
and to run event loop use `EV::run`. Accoring to its [doc](https://metacpan.org/pod/EV) the event loop stops when all watchers stoped (or EV::break was called). So, when the connection error occures the module clears all watchers and the event loop in turn would automatically be stopped.

2) I added the code which allows the following: now you can specify callbacks for some events which can occur during working with connection
```perl
use AnyEvent;

use DR::Tarantool::MsgPack::AsyncClient;

my $cv = AnyEvent->condvar;
DR::Tarantool::MsgPack::AsyncClient->connect(
    host => $host,
    port => $port,
    on   => {
          error        => sub { warn "error occured: "     . shift->error; $cv->send },
          connfail     => sub { warn "connection failed: " . shift->error; $cv->send },
          reconnecting => sub { warn "reconnecting" },
    },
    sub {
       my $self = shift;
       warn "CONNECTED";
       return $cv->send unless ref $self;
       $self->call_lua(test_func => [3, 4, 5], sub { warn "OK!"; $cv->send })
    }
);

$cv->recv;
```
So, if some error occures you are able to handle it with callbacks you specified to `send()` some condvars or do anything else you need.

## One more note which concerns **SyncClient**: in case of errors it raises exceptions.
So when calling any DR::Tarantool functions you should catch possible errors using `eval {}`
```perl
use DR::Tarantool::MsgPack::SyncClient;

my $connection;
eval {
  $connection = DR::Tarantool::MsgPack::SyncClient->connect(
      host => $host,
      port => $port,
      on   => {
            error        => sub { warn "error occured: "     . shift->error },
            connfail     => sub { warn "connection failed: " . shift->error },
            reconnecting => sub { warn "reconnecting" },
      },
  );
} or warn "Error occured when connecting: $@";
```
The callback would also be called in this case. It's up to you: you can analyze `$@` for possible errors or use callbacks.

The same thing is with using existing `$connection` object:
```perl
my $data = eval { $connection = call_lua(my_lua_func => [@args]) }
   or warn "Error occured when calling function 'my_lua_func': $@";
```

**Comment by Awety** [comment]
Merged into master.
```sh
$ git merge origin/loosing-connection-epoll_wait --no-ff
Merge made by the 'recursive' strategy.
 Changes                                 |  7 +++++++
 README.md                               |  5 ++---
 lib/DR/Tarantool.pm                     |  2 +-
 lib/DR/Tarantool/AEConnection.pm        | 21 ++++++++++++++-------
 lib/DR/Tarantool/LLClient.pm            | 29 ++++++++++++++++++++++-------
 lib/DR/Tarantool/MsgPack/AsyncClient.pm | 12 ++++++++++++
 6 files changed, 58 insertions(+), 18 deletions(-)
```
