### ISSUE TITLE
Broken conversion from 'undef' to 'nil'

### ISSUE THREAD

**Issue by fsitedev** [tarantool/tarantool-perl#16]
Calling lua procedure from perl with 'undef' param leads to 'cdata<void *>: NULL' on the tarantool side.

**Comment by Awety** [comment]
Well, I looked through the xs-code, even dumped binary msgpacked structure -- everything is alright, the message is encoded according to msgpack specification.

It turned out the problem lies in tarantool: https://github.com/tarantool/tarantool/issues/1666.
In lua function it returns msgpack.NULL instead of pure lua nil. So, let's rate this tarantool issue and wait for this to be fixed.

The only walkaround way to use this in our lua procedures is to make checks somehow like this
```lua
if (x == nil) then
...
end
```
and NOT like `if (x)`, because this "not really nil" is boolean `true`.
